version: '3'
services:
  # Nginx server configuration   
  website-service:
    build: ./nginx
    container_name: website_container
    depends_on:
      - mysql-service
      - php-service
    links:
      - mysql-service
      - php-service
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  # php-fpm configuration
  php-service:
    build: ./php
    container_name: php_container
    volumes:
      - ./website:/usr/share/nginx/html
      # - ./php:/usr/local/etc/php/php.ini
  # MySQL configuration
  mysql-service:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=root123
    # ports:
    #     - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
volumes:
  dbdata:
