version: '3'
services:
  # Nginx server configuration   
  website-service:
    image: nginx:1.19
    container_name: website_container
    depends_on:
      - setup-service
      - percona-service
      - php-service
    volumes:
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/htpasswd/.htpasswd:/usr/share/nginx/.htpasswd
      - ./nginx/ssl/site.crt:/etc/ssl/certs/site.crt
      - ./nginx/ssl/site.key:/etc/ssl/private/site.key
      - ./website:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  # php-fpm configuration
  php-service:
    build: ./php
    container_name: php_container
    depends_on:
      - percona-service
    volumes:
      - ./website:/usr/share/nginx/html
  # MySQL configuration
  percona-service:
    image: percona:8
    container_name: percona_container
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - dbdata:/var/lib/mysql
  setup-service:
    build: ./setup
    container_name: setup_container
    environment:
      - HTUSER=${HTUSER}
      - HTPASS=${HTPASS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./nginx/htpasswd:/tmp/htpasswd
      - ./nginx/ssl:/tmp/ssl
      - ./website:/tmp/website
volumes:
  dbdata:
