version: '3'
services:
  # Nginx server configuration   
  website-service:
    build:
      context: ./nginx
      args:
        - HTUSER=${HTUSER}
        - HTPASS=${HTPASS}
    container_name: website_container
    depends_on:
      - htpasswd-service
      - percona-service
      - php-service
    volumes:
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/htpasswd/.htpasswd:/usr/share/nginx/.htpasswd
      - ./website:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  # php-fpm configuration
  php-service:
    build: ./php
    container_name: php_container
    depends_on:
      - percona-service
    volumes:
      - ./website:/usr/share/nginx/html
  # MySQL configuration
  percona-service:
    image: percona:8
    container_name: percona_container
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - dbdata:/var/lib/mysql
  htpasswd-service:
    build: ./nginx/htpasswd
    container_name: htpasswd_container
    environment:
      - HTUSER=${HTUSER}
      - HTPASS=${HTPASS}
    volumes:
      - ./nginx/htpasswd:/tmp/htpasswd
volumes:
  dbdata:
